#本博客素材取自https://github.com/Gaohaoyang/gaohaoyang.github.io
#第一版介绍地址为http://jekyllthemes.org/themes/cool-concise-high-end/


#指定启动Jekyll服务时的端口号，访问的地址为http://127.0.0.1:port/
port: 1234
#指定并配置Markdown解析器（2016年05月01日起，GitHubPages将只支持kramdown作为唯一的Markdown引擎）
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


title: 半步多博客
brief-intro: ""

#配置页面头部<link rel="canonical" href="https://jadyer.github.io/2016/10/17/first-blog/">
url: "https://jadyer.github.io"

#the subpath of your site, e.g. /blog
baseurl: ""

#footer下方显示的联系方式
#twitter_username: jadyer
#facebook_username: jadyer
#github_username: jadyer
#email: jadyer@yeah.net
#weibo_username: jadyer
#zhihu_username: jadyer
#linkedIn_username: jadyer

#评论（指定多说或Disqus的short_name）
#disqus_shortname: jadyer
duoshuo_shortname: jadyer

#统计（指定Baidu或Google的统计ID）
#google_analytics_id: UA-72449510-4
baidu_tongji_id: a1ec472ee05eea50838e5dab0a70c4a0





# url
category_dir: category/
tag_dir: tag/





#博文分页的配置
gems: [jekyll-paginate]
paginate: 10
#博文的固定链接形式
permalink: /:year/:month/:day/:title/
#摘要分割符号（Jekyll在解析文章时便可提取摘要）
excerpt_separator: "\n\n\n\n"








#layout: post                                   #这个博客的布局文件
#title: 在Github上搭建自己的Jekyll博客             #博客标题
#category: 工具                                  #博客分类
#tags: Jekyll                                   #博客标签
#keywords: Jekyll,Github                        #自定义常量
#description:                                   #自定义常量
#_includes 可以在模板中随时包含的文件
#_layouts 布局文件，在博客头配置中可以选择
#pages 站内固定的页面
#public 公共资源，包括js,css,img等，还有我博客中调用的图片，我都放这里
#index.html 站点的首页，整个站的入口文件
#sitemap.txt 给搜索引擎看的，如何爬取这个站