#本博客素材取自https://github.com/Gaohaoyang/gaohaoyang.github.io
#第一版介绍地址为http://jekyllthemes.org/themes/cool-concise-high-end/

#指定启动Jekyll服务时的端口号，访问的地址为http://127.0.0.1:port/
port: 1234

title: 半步多博客
brief-intro: 站在云端，敲下键盘，望着通往世界另一头的那扇窗，只为做那读懂0和1的人。。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jadyer.github.io2222"

permalink: /:year/:month/:day/:title/

# other links
#twitter_username: gaohaoyang126
#facebook_username: gaohaoyang.water
#github_username: jadyer
#email: jadyer@yeah.net
#weibo_username: 3115521wh
#zhihu_username: gaohaoyang
#linkedIn_username: gaohaoyang
#dribbble_username:

#description_footer: 本站记录我的所见所得！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: jadyer
#disqus_shortname: gaohaoyang

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: a1ec472ee05eea50838e5dab0a70c4a0
#google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
